name: dropdown_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dropdown_button2: ^2.3.9
  json_annotation: ^4.9.0
  http: ^1.5.0
  flutter_svg: ^2.1.0
  provider: ^6.1.5
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
